/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlacceso.vista;

import controlacceso.controlador.controlaPerfiles;
import controlacceso.modelo.modeloPerfiles;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
;

/**
 *
 * @author tuxmi
 */
public final class perfiles extends javax.swing.JInternalFrame {
    
    
    /**
     * Creates new form perfiles
     * @throws java.sql.SQLException
     */
    public perfiles() throws SQLException {
        initComponents();
        llenaTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanelCrear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        perfilNombre = new javax.swing.JTextField();
        perfilEstado = new javax.swing.JCheckBox();
        btnGuardaPerfil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPerfiles = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Perfil de usuarios");
        setName(""); // NOI18N

        jLabel1.setText("Nombre de Perfil");

        jLabel4.setText("Estado");

        btnGuardaPerfil.setText("Guardar");
        btnGuardaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaPerfilActionPerformed(evt);
            }
        });

        tablaPerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id Perfil", "Nombre", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPerfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPerfilesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPerfiles);

        javax.swing.GroupLayout jPanelCrearLayout = new javax.swing.GroupLayout(jPanelCrear);
        jPanelCrear.setLayout(jPanelCrearLayout);
        jPanelCrearLayout.setHorizontalGroup(
            jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearLayout.createSequentialGroup()
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perfilEstado)
                            .addComponent(perfilNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardaPerfil)))
                    .addGroup(jPanelCrearLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanelCrearLayout.setVerticalGroup(
            jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(perfilNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(perfilEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardaPerfil)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Crear", jPanelCrear);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnGuardaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaPerfilActionPerformed
        try {
            // TODO add your handling code here:
            String nombrePerfil;
            boolean estadoPerfil;

            nombrePerfil = perfilNombre.getText();
            estadoPerfil = perfilEstado.isSelected();

//            int estadoInsert=controlaPerfiles.cIngresaPerfiles(nombrePerfil, estadoPerfil);
            int estadoInsert = modeloPerfiles.insertaPerfiles(nombrePerfil, estadoPerfil);
            if(estadoInsert==1){
                llenaTabla();
                JOptionPane.showMessageDialog(null, "Perfil Ingresado correctamente");
                perfilNombre.setText("");
                perfilEstado.setSelected(false);

            }else{
                JOptionPane.showMessageDialog(null, "Error al ingresar el perfil");
            }

        } catch (SQLException ex) {
            Logger.getLogger(perfiles.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGuardaPerfilActionPerformed

    private void tablaPerfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPerfilesMouseClicked
        // TODO add your handling code here:
        int fila;
        boolean estado = false;
        String idPerfil, nombrePerfil, estadoS;
        
        fila = tablaPerfiles.getSelectedRow();
        idPerfil = tablaPerfiles.getValueAt(fila, 0).toString();
        nombrePerfil = tablaPerfiles.getValueAt(fila, 1).toString();
        estadoS = tablaPerfiles.getValueAt(fila, 2).toString();
        
//convierte el estadoS que es string y toma valor 1 o 0 en true o false         
        estado = estadoS.equals("1") ? true : false;
        
        perfilNombre.setText(nombrePerfil);
        perfilEstado.setSelected(estado);
//seguir trabajando desde aqui        
                
//        perfilEstado.setSelected(estado);
        System.out.println("el estado es: " + estado);
    }//GEN-LAST:event_tablaPerfilesMouseClicked

    
    public void llenaTabla(){
        
        //busca en la base de datos y llena la tabla

        DefaultTableModel modelo = new DefaultTableModel();
        tablaPerfiles.setModel(modelo);
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Estado");
        
        try {
//construlle modelo perfiles e importa los datos a esta clase
            ResultSet rs;
            modeloPerfiles mp = new modeloPerfiles();
            rs = mp.mConsultaPerfiles();

            ResultSetMetaData rsmd = rs.getMetaData();

//ingresa las filas a un objeto

            while(rs.next()){
                Object[] fila = new Object[rsmd.getColumnCount()];
                for (int i = 0; i<rsmd.getColumnCount(); i++){
                    fila[i] = rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            //        fin codigo migrado modelo
            modeloPerfiles.cierraSesion();

        } catch (SQLException ex) {
            Logger.getLogger(perfiles.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardaPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCrear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JCheckBox perfilEstado;
    private javax.swing.JTextField perfilNombre;
    private javax.swing.JTable tablaPerfiles;
    // End of variables declaration//GEN-END:variables
}
