/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlacceso.vista;

import controlacceso.controlador.controlaUsuarios;
import controlacceso.modelo.modeloPerfiles;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form usuarios
     */
    public usuarios() throws SQLException {
        initComponents();
        llenajComboPerfiles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelId = new javax.swing.JLabel();
        jLabelMuestraId = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextNombreUsuario = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jCheckEstado = new javax.swing.JCheckBox();
        jLabelPerfil = new javax.swing.JLabel();
        jComboPerfiles = new javax.swing.JComboBox<>();
        jButtonGuardar = new javax.swing.JButton();
        jLabelContrasena = new javax.swing.JLabel();
        jPasswordUsuario = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Usuarios de Sistema");
        setToolTipText("");

        jLabelId.setText("Id");

        jLabelNombre.setText("Nombre: *");

        jTextNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreUsuarioActionPerformed(evt);
            }
        });

        jLabelEstado.setText("Estado: *");

        jCheckEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckEstadoActionPerformed(evt);
            }
        });

        jLabelPerfil.setText("Perfil");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelContrasena.setText("Contraseña:*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPerfil))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMuestraId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelContrasena))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckEstado)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextNombreUsuario)
                                        .addComponent(jPasswordUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(jButtonGuardar)))))
                        .addContainerGap(457, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGuardar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelMuestraId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelId)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelContrasena)
                            .addComponent(jPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEstado)
                            .addComponent(jCheckEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPerfil)
                            .addComponent(jComboPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreUsuarioActionPerformed

    private void jCheckEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckEstadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckEstadoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
//guarda usuarios
        
//selecciona el perfil y obtiene el id del jComboBox
    perfil perfil = (perfil) jComboPerfiles.getSelectedItem();
    int idPerfil = Integer.parseInt(perfil.getID());
    
    String pass = new String(jPasswordUsuario.getPassword());
    
 //comprueba que el tama;o de la contrase;a y el usuario sean mayores a 8   
    if(pass.length()<8 || jTextNombreUsuario.getText().length()<8){
        JOptionPane.showMessageDialog(null, "El numero de caracteres para el usuario y la contrase;a debe ser igual o mayor a 8");
        jTextNombreUsuario.setText("");
        jPasswordUsuario.setText("");
        
    }else{    
        try {
 //crea un objeto id para obtener el id del perfil seleccionado en el jComboBox           
            perfil perfilObjeto = (perfil) jComboPerfiles.getSelectedItem();
            
            //llama metodo para ingresar usuarios
            controlaUsuarios.cIngresaUsuario(jTextNombreUsuario.getText(), new String(jPasswordUsuario.getPassword()), jCheckEstado.isSelected(), Integer.parseInt(perfilObjeto.getID()));
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    }//GEN-LAST:event_jButtonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JCheckBox jCheckEstado;
    private javax.swing.JComboBox<String> jComboPerfiles;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMuestraId;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPerfil;
    private javax.swing.JPasswordField jPasswordUsuario;
    private javax.swing.JTextField jTextNombreUsuario;
    // End of variables declaration//GEN-END:variables

    private void llenajComboPerfiles() throws SQLException {
        
        DefaultComboBoxModel jcp = new DefaultComboBoxModel();
        jComboPerfiles.setModel(jcp);
//consulta los perfiles disponibles en la base de datos        
        ResultSet rs = modeloPerfiles.mConsultaPerfiles("");
                
        while(rs.next()){
//envia los datos de la consulta al metodo perfil
            jcp.addElement(new perfil(rs.getString(2), rs.getString(1)));
        }
        modeloPerfiles.cierraSesion();
        
    }
    public class perfil {
//almacena los perfiles del jComboPerfiles y envia el id cuando se llama
          private String nombre;
          private String id ;
      
          public perfil(String nombre , String id ) {
                this.nombre=nombre;
                this.id=id;
          }
     
            public String getID(){
                return id ;
            }
     
            public String toString() {
                return nombre ;
            }
    }
}
